apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ .Release.Name }}-production-frontend
  labels:
    app: {{ .Release.Name }}-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-front
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-front
    spec:
      containers:
      - name: {{ .Release.Name }}-production-frontend
        image: {{ .Values.container.frontendImage }}
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_BACKEND_URL
          value: http://nyamtsu.pp.ua/api
        resources:
          requests:
            memory: "512Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "125m"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: {{ .Release.Name }}-production-frontend-autoscaling
  labels:
    app: {{ .Release.Name }}-front
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: {{ .Release.Name }}-front
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
